<!-- subject: Python tips and tricks -->
<!-- date: 2016-09-01 22:07:05 -->
<!-- tags: python -->
<!-- categories: Articles, English, Techblog -->

<p>Python! My old nemesis, we meet again.  Actually, we meet all the
  time, but despite that there are always things which I cannot quite
  remember how to do and need to look them up.  To help with the
  searching, here there are collected in one post:

<ul>
  <li><a href=/2016/python-tricks/#date>Converting a date into a timestamp</a>
  <li><a href=/2016/python-tricks/#rise>Re-rising Python exception preserving back-trace</a>
  <li><a href=/2016/python-tricks/#flatten>Flattening a list in Python</a>
</ul>

<!-- EXCERPT -->

<h2 id=date>Converting a date into a timestamp</h2>

<p>Neither <code>datetime.date</code>
  nor <code>datetime.datetime</code> has a method turning it into
  a timestamps, i.e. seconds since Unix epoch.  Programmers might be
  tempted to use <code>strftime('%s')</code> or
  <code>time.mktime</code> but that may result in a disaster:

<pre>
>>> import datetime, time
>>> now, ts = datetime.datetime.utcnow(), time.time()
>>> ts - int(now.strftime('%s'))
7200.1702790260315
>>> ts - time.mktime(now.timetuple())
7200.1702790260315
</pre>

<p>In both cases, expected value is around zero (since it measures
  time between <code>utcnow</code> and <code>time</code> calls) but in
  practice it is close to the value of local timezone offset (UTC+2 in
  the example).  Both methods take local timezone into account which
  is why the offset is added.

<p>The proper solution is <code>calendar.timegm</code> (which for some
  bizarre reason is not included in <code>time</code> module; yet
  another proof Python is much less ‘clean’ than its advocates argue):

<pre>
import calendar, datetime, time
now, ts = datetime.datetime.utcnow(), time.time()
print ts - calendar.timegm(now.timetuple())  # prints: 0.308976888657
</pre>

<h2 id=rise>Re-rising Python exception preserving back-trace</h2>

<pre>
import sys

exc_info = []

def fail(): assert False

def run():
    try: fail()
    except: exc_info[:] = sys.exc_info()

def throw(): raise exc_info[0], exc_info[1], exc_info[2]

def call_throw(): throw()

if not run(): call_throw()</pre>

<p>When <code>throw</code> rises the exception again, back-trace will
contain all frames that led up to having the exception caught
in <code>run</code>:

<pre>
$ python exc.py
Traceback (most recent call last):
  File "exc.py", line 15, in <module>
    if not run(): call_throw()
  File "exc.py", line 13, in call_throw
    def call_throw(): throw()
  File "exc.py", line 8, in run
    try: fail()
  File "exc.py", line 5, in fail
    def fail(): assert False
AssertionError</pre>

<p>This is a bit like bare <code>rise</code> in <code>except</code>
clause but performing the re-rising at arbitrary later time.

<h2 id=flatten>Flattening a list in Python</h2>

<p>To turn a list of lists (or in more generic terms, an iterable of
iterables) into a single iterable use one of:

<pre>
def flatten(sequences):
    return itertools.chain.from_iterable(sequences)

def flatten(sequences):
    return (x for lst in sequences for x in lst)</pre>

<p>(If you feel confused about nested comprehension don’t feel
bad — it’s syntax is broken.  The thing to remember is that you write
a normal nested for-if-for-if-… sequence but then put the final
statement at the beginning of the line instead of at the end).

<p>If all elements are known to be lists or tuples,
using <code>sum</code> may be considered easier:

<pre>
def flatten(lists):
    return sum(lists, [])

def flatten(tuples):
    return sum(tuples, ())</pre>
